[package]
name = "spl_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"

[dependencies.env_logger]
version = "0.9"
optional = true

[dependencies.clap]
version = "4.1.8"
features = ["derive"]
optional = true

[features]
cli = ["clap", "env_logger"]
